Support completely unreliable datachannels
webrtc-rs/data pull request #5
Opened 2022-04-30 23:15 UTC by connorcarpenter

It appears that DataChannel parameters: id maxRetransmits & maxPacketLifetime were not translated completely from https://github.com/pion/webrtc/blob/master/datachannel.go#L26

These parameters are able to have a value of nil in Pion, which allows for setup of datachannels which are completely unordered & unreliable. There's a big difference between an id or maxRetransmits of nil vs 0, which webrtc-rs currently conflates.

This will allow interop with https://github.com/triplehex/webrtc-unreliable .

This PR requires the usage of the following PRs to function correctly:
(incoming..)

2022-05-06 00:09 UTC, rainliu commented
@connorcarpenter, thank you for your PR. Could you fix the test and fmt/clippy issue? Thanks.

2022-05-06 01:04 UTC, connorcarpenter commented
Thank you for the heads up rainliu :+1: Hoping I can get to this soon, bit of a busy weekend coming up ..

2022-06-15 11:58 UTC, melekes requested changes
thanks for contributing 👍

2022-06-15 11:58 UTC, melekes commented on src/message/message_channel_open.rs
> +        let has_reliability_param: u8 = match self.reliability_parameter.is_some() {
```suggestion
        if let Some(p) = self.reliability_parameter {
          buf.put_u8(1);
          buf.put_u16(p);
        } else {
          buf.put_u8(0);
        }
```

2022-08-23 11:52 UTC, k0nserv commented
We have migrated this crate to the monorepo([`webrtc-rs/webrtc`](https://github.com/webrtc-rs/webrtc/)) please re-open this pull request over there.

2022-08-23 11:52 UTC, closed without merging